# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04b431a4111183770d0b8d968c22448e4779f0cc2d546e0c7f182bf1d2af84e765a3ac6ec8392fd998867efe7a3f414d324920f2370103c13eccc5a18ca63d20

test:
  secret_key_base: 08b538442479fd35f33834303804ac1b929d4ae65eccd815f68d2a7ae3accc8f1f7cb5ae1dd06f63d48cb60553cdbc32370ee4d7848005d5cf00c2f73e5e8505

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
